services:
  pxc_mysql1:
    image: percona/percona-xtradb-cluster:5.6
    container_name: pxc_mysql1
    privileged: true
    restart: always
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: Qazxsw23edc!!!
      MYSQL_DATABASE: fido
      MYSQL_USER: fido
      MYSQL_PASSWORD: Qazx
      CLUSTER_NAME: PXC
      XTRABACKUP_PASSWORD: Qazxsw23edc!!!

      WSREP_SST_METHOD: xtrabackup-v2
      PXC_STRICT_MODE: MASTER
      PXC_BOOTSTRAP: 1  

    volumes:
      - ./v1pxc:/var/lib/mysql
